[build]
  publish = "."
  functions = "netlify/functions"
  
# Node.js Version und Umgebungseinstellungen
[build.environment]
  NODE_VERSION = "18.18.0"
  
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

# Weiterleitungen f√ºr API-Aufrufe an Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Hauptseite bei Direktzugriff
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
